crawler:
    build: .
    links:
        - redis
        - influxdb
    command: /app/crawler -depth 2 -seed-url 'https://www.youtube.com/watch?v=zNdkrtfZP8I' -search='^.*\/watch\?v=[a-zA-Z0-9\-]+'

redis:
    image: redis:latest
    ports:
        - 6379:6379

influxdb:
    image: tutum/influxdb:latest
    ports:
        - 8086:8086
    environment:
        - PRE_CREATE_DB="crawler;telegraf"

telegraf:
    image: telegraf:latest
    volumes:
        - ./conf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
        - redis
        - influxdb

chronograf:
    image: chronograf:latest
    ports:
        - 10000:10000
